### ISSUE TITLE
Маленькие лайки :thinking:

### ISSUE THREAD

**Issue by prostomarkeloff** [neyasbltb88/vk-theme-fess#2]
Во-первых, большое спасибо за тему, выглядит очень круто!
Но есть один недостаток, какие-то лайки довольно маленькие, не планируется ли их увеличить?)

![image](https://user-images.githubusercontent.com/28061158/67892341-974a2c00-fb65-11e9-9120-b5d8c55476c3.png)

**Comment by neyasbltb88** [comment]
Спасибо за проявленный интерес к теме! Дело в том, что я специально их уменьшил, ибо обычно ставлю масштаб 110%-125% на страницах вк. Сделал отдельный бранч, в котором [вернул](https://github.com/neyasbltb88/vk-theme-fess/commit/c383ea2b97fb698da5b48aa752391e075f9ae9a2) оригинальные размеры блоку лайков: [vk-theme-fess.css](https://github.com/neyasbltb88/vk-theme-fess/blob/big_likes/vk-theme-fess.css)

**Comment by prostomarkeloff** [comment]
Спасибо!
